apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: budget-tracker-api
  labels:
    app: budget-tracker
    environment: production
  annotations:
    # Cloud Run specific annotations
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        
        # Cloud SQL connector (uncomment if using Cloud SQL)
        # run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:INSTANCE_NAME
        
        # VPC connector (uncomment if using VPC)
        # run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
        # run.googleapis.com/vpc-access-egress: private-ranges-only
        
        # Execution environment
        run.googleapis.com/execution-environment: gen2
        
        # Startup CPU boost
        run.googleapis.com/startup-cpu-boost: "true"
        
        # Session affinity (optional, for sticky sessions)
        # run.googleapis.com/sessionAffinity: "true"
    spec:
      # Service account with necessary permissions
      serviceAccountName: budget-tracker-sa@PROJECT_ID.iam.gserviceaccount.com
      
      # Container timeout (max request duration)
      timeoutSeconds: 300
      
      containers:
      - name: budget-tracker-api
        image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/budget-tracker-api:TAG
        
        ports:
        - name: http1
          containerPort: 3000
        
        # Resource limits
        resources:
          limits:
            cpu: "1000m"        # 1 vCPU
            memory: "512Mi"     # 512 MiB RAM
          requests:
            cpu: "500m"         # 0.5 vCPU minimum
            memory: "256Mi"     # 256 MiB minimum
        
        # Startup probe (before ready)
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 10
          timeoutSeconds: 3
        
        # Liveness probe (restart if fails)
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3
        
        # Readiness probe (receive traffic when ready)
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          timeoutSeconds: 3
        
        # Environment variables from Secret Manager
        env:
        # Server configuration
        - name: NODE_ENV
          value: "production"
        
        - name: PORT
          value: "3000"
        
        # Database (from Secret Manager)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: budget-tracker-database-url
              key: latest
        
        # JWT Secrets (from Secret Manager)
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: budget-tracker-jwt-secret
              key: latest
        
        # Social Authentication - Google
        - name: GOOGLE_WEB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-google-web-client-id
              key: latest
        
        - name: GOOGLE_IOS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-google-ios-client-id
              key: latest
        
        - name: GOOGLE_ANDROID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-google-android-client-id
              key: latest
        
        # Social Authentication - Apple
        - name: APPLE_BUNDLE_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-apple-bundle-id
              key: latest
        
        # Social Authentication - Facebook
        - name: FACEBOOK_APP_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-facebook-app-id
              key: latest
        
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: budget-tracker-facebook-app-secret
              key: latest
        
        # Google Cloud Storage
        - name: GCS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: budget-tracker-gcs-bucket-name
              key: latest
        
        - name: GCS_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-gcs-project-id
              key: latest
        
        # Veryfi OCR
        - name: VERYFI_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budget-tracker-veryfi-client-id
              key: latest
        
        - name: VERYFI_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: budget-tracker-veryfi-client-secret
              key: latest
        
        - name: VERYFI_USERNAME
          valueFrom:
            secretKeyRef:
              name: budget-tracker-veryfi-username
              key: latest
        
        - name: VERYFI_API_KEY
          valueFrom:
            secretKeyRef:
              name: budget-tracker-veryfi-api-key
              key: latest
        
        # Firebase Admin (Push Notifications)
        - name: FIREBASE_ADMIN_JSON_BASE64
          valueFrom:
            secretKeyRef:
              name: budget-tracker-firebase-admin-json
              key: latest
        
        # Cron Secret
        - name: CRON_SECRET
          valueFrom:
            secretKeyRef:
              name: budget-tracker-cron-secret
              key: latest
        
        # CORS Configuration
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: budget-tracker-cors-allowed-origins
              key: latest
        
        # Rate Limiting
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        
        # Logging
        - name: LOG_LEVEL
          value: "info"
  
  traffic:
  - percent: 100
    latestRevision: true

